= Add support for gRPC
:author:            Harald Pehl
:email:             hpehl@redhat.com
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -
:issue-base-url:    https://issues.redhat.com/browse

== Overview

The goal of this RFE is to provide support for gRPC in WildFly. https://grpc.io/[gRPC] is a high-performance RPC framework.
It can efficiently connect services implemented using various languages and frameworks.
It is also applicable in the last mile of distributed computing to connect devices, mobile applications, and browsers to backend services.

This RFE will add a gRPC subsystem to WildFly.
It:

* supports implementing gRPC services
// * supports consuming gRPC services
* integrates with other WildFly components such as CDI, MP health, security or transaction
* allows plain-text communication as well as TLS, and TLS with mutual authentication

The gRPC subsystem provides a default configuration for all gRPC services,
// and clients. 
which is accessible through the management client.
The major part of the gRPC subsystem is a deployment unit processor which scans deployments for
gRPC services.
//, clients and interceptors.
//The default configuration can be overriden on a deployment basis.

The gRPC subsystem defines a https://docs.wildfly.org/galleon/#_layers[Galleon layer] which will be responsible for providing the gRPC subsystem.

==== Feature maturity

The feature is intended to be introduced at the *Preview* level.
////
==== Nice-to-Have requirements

* Identity authorization
* Interceptors
* Server side client configuration
* Per deployment configuration
* More extensive testing
////
==== Jakarta RPC Specification

There's a Jakarta EE proposal for a specification called https://projects.eclipse.org/reviews/jakarta-rpc-creation-review[Jakarta RPC].
This specification aims to make gRPC services and clients easier to implement in Java.
The specification proposes a programming model for gRPC similar to JAX-RS and MicroProfile REST Client.
At the time of writing, the proposal is not an official specification yet and very much wip.

The scope of this RFE is *not* to implement Jakarta RPC.
If it becomes a Jakarta EE specification at some point in time, there might be a follow-up RFE to support such a specification.
Instead, this RFE is about to bring gRPC support to WildFly.

== Issue Metadata

=== Issue

* {issue-base-url}/WFLY-15495[WFLY-15495] "Add support for gRPC"
* {issue-base-url}/EAP7-1819[EAP7-1819] "Add support for gRPC"

=== Related Issues

* {issue-base-url}/WFLY-13530[WFLY-13530] "REST Integration with grpc (high performance, open-source universal RPC framework)
* {issue-base-url}/EAP7-1536[EAP7-1536] "REST Integration with grpc (high performance, open-source universal RPC framework)"

=== Dev Contacts

* mailto:hpehl@redhat.com[Harald Pehl]
* mailto:rsigal@redhat.com[Ron Sigal]

=== QE Contacts

* TBD

=== Testing By

[x] Engineering

[ ] QE

=== Affected Projects or Components

* WildFly

== Requirements

=== Hard Requirements

* The gRPC subsystem opens and manages a port for processing gRPC invocations.
* The gRPC subsystem detects and integrates gRPC server deployments.
* Support for server side interceptors.
* The gRPC subsystem provides a default configuration.
* The Galleon layer must provide the gRPC subsystem dependencies.
* The gRPC subsystem integrates with the Elytron subsystem to provide TLS, and TLS with mutual authentication
* Management API needs maturity level metadata.
* A gRPC chapter in the WildFly https://github.com/wildfly/wildfly/tree/main/docs/src/main/asciidoc/_developer-guide[developer guide]

=== Nice-to-Have Requirements

* The gRPC subsystem integrates with the Elytron subsystem to provide identity authorization.
* Support for client side interceptors
* gRPC services, clients and interceptors can be deployed independently of each other [???]
* gRPC services, clients and interceptors can be configured independently of each other
* WildFly quickstart for gRPC clients, services and interceptors
* Support of https://github.com/grpc/grpc/blob/master/doc/health-checking.md[gRPC health check]
* Support of https://github.com/grpc/grpc/blob/master/doc/server-reflection.md[gRPC relfection]
* Support of https://smallrye.io/smallrye-mutiny/[Mutiny] API

=== Non-Requirements

* Support of Jakarta gPRC specification

=== Default Configuration

The gRPC subsystem provides a default configuration which is applied to all gRPC services.
// and clients and which can be overriden on a deployment basis.
////
==== Client

`plain-text`::
Whether `plain-text` should be used instead of TLS.
Enables by default, except it TLS/SSL is configured.
In this case, `plain-text` is disabled.

`keep-alive-time`::
The duration after which a keep alive ping is sent.

`flow-control-window`::
The flow control window in bytes.
Default is 1MiB.

`idle-timeout`::
The duration without ongoing RPCs before going to idle mode.

`keep-alive-timeout`::
The amount of time the sender of a keep alive ping waits for an acknowledgement.

`keep-alive-without-calls`::
Whether keep-alive will be performed when there are no outstanding RPC on a connection.

`max-hedged-attempts`::
The max number of hedged attempts.

`max-retry-attempts`::
The max number of retry attempts.
Retry must be explicitly enabled.

`max-trace-events`::
The maximum number of channel trace events to keep in the tracer for each channel or sub-channel.

`max-inbound-message-size`::
The maximum message size allowed for a single gRPC frame (in bytes).
Default is 4 MiB.

`max-inbound-metadata-size`::
The maximum size of metadata allowed to be received (in bytes).
Default is 8192B.

`per-rpc-buffer-limit`::
The per RPC buffer limit in bytes used for retry.

`retry`::
Whether retry is enabled.
Note that retry is disabled by default.

`retry-buffer-size`::
The retry buffer size in bytes.

`user-agent`::
Use a custom user-agent.

`compression`::
The compression to use for each call.
The accepted values are gzip and identity.

==== Server
////
////
`handshake-timeout`::
The gRPC handshake timeout.

`max-inbound-message-size`::
The max inbound message size in bytes.

`max-inbound-metadata-size`::
The max inbound metadata size in bytes

`ssl.client-auth`::
Configures the engine to require/request client authentication.
NONE, REQUEST, REQUIRED

`plain-text`::
Disables SSL, and uses plain text instead.
If disabled, configure the ssl configuration.

`alpn`::
Whether ALPN should be used.

`netty.keep-alive-time`::
Sets a custom keep-alive duration.
This configures the time before sending a keepalive ping when there is no read activity.

`compression`::
gRPC compression, e.g. "gzip"
////

* *flow-control-window*: Sets the flow control window in bytes. Setting flowControlWindow disables auto flow control
   tuning; use "initial-flow-control-window" to enable auto flow control tuning. If not
   called, the default value is 1024 * 1024 with auto flow control tuning. The type is `int` and the unit is seconds.

* *handshake-timeout*:  Sets the permitted time for new connections to complete negotiation handshakes before being
   killed. The type is `long` and the unit is seconds.
   
* *initial-flow-control-window*: Sets the initial flow control window in bytes. Setting initial flow control window enables auto
   flow control tuning using bandwidth-delay product algorithm. To disable auto flow control
   tuning, use "flow-control-window". By default, auto flow control is enabled with
   initial flow control window size of 1024 * 1024. The type is `int` and the unit is seconds.
   
* *keep-alive-time*: Sets a custom keepalive time, the delay time for sending next keepalive ping. An unreasonably
   small value might be increased, and `Long.MAX_VALUE` seconds or an unreasonably
   large value will disable keepalive. The default is two hours. The type is `long` and the unit is seconds.

* *keep-alive-timeout*: Sets a custom keepalive timeout, the timeout for keepalive ping requests. An unreasonably small
   value might be increased. The default is 20 seconds. The type is `long` and the unit is seconds.

* *key-manager-name*: Refers to a key manager defined in the Elytron subsystem. The type is `String`, and no key manager is
   set by default.

* *max-concurrent-calls-per-connection*: The maximum number of concurrent calls permitted for each incoming connection. Defaults to no
   limit. The type is `int`.
   
* *max-connection-age*: Sets a custom max connection age; a connection lasting longer than which will be gracefully
   terminated. An unreasonably small value might be increased.  A random jitter of +/-10% will be
   added to it. `Long.MAX_VALUE` seconds or an unreasonably large value will disable
   max connection age. The type is `long` and the unit is seconds. The default value disables max connection age.
   
* *max-connection-age-grace*: Sets a custom grace time for the graceful connection termination. Once the max connection age
   is reached, RPCs have the grace time to complete. RPCs that do not complete in time will be
   cancelled, allowing the connection to terminate. `Long.MAX_VALUE` seconds or an
   unreasonably large value are considered infinite. The type is `long` and the unit is seconds. The default value is
   essentially infinite.
   
* *max-connection-idle*: Sets a custom max connection idle time; connections being idle for longer than which will be
   gracefully terminated. Idleness duration is defined since the most recent time the number of
   outstanding RPCs became zero or the connection establishment. An unreasonably small value might
   be increased. `Long.MAX_VALUE` seconds or an unreasonably large value will disable max connection idle.
   The type is `long` and the unit is seconds. The default value is essentially infinite.
   
* *max-inbound-message-size*: Sets the maximum message size allowed to be received on the server. If not set,
   defaults to 4 MiB. The default provides protection to servers who haven't considered the
   possibility of receiving large messages while trying to be large enough to not be hit in normal
   usage. The default is 4 * 1024 * 1024. The type is `int`.

* *max-inbound-metadata-size*: Sets the maximum size of metadata allowed to be received. This is cumulative size of the
   entries with some overhead, as defined for http://httpwg.org/specs/rfc7540.html#rfc.section.6.5.2
   HTTP/2's SETTINGS_MAX_HEADER_LIST_SIZE. The default is 8 KiB. The type is `int`.

* *permit-keep-alive-time*: Specify the most aggressive keep-alive time clients are permitted to configure. The server will
   try to detect clients exceeding this rate and when detected will forcefully close the
   connection. The default is 5 minutes. The type is `long` and the unit is seconds. *Note.* Even though a default is
   defined that allows some keep-alives, clients must not use
   keep-alive without approval from the service owner. Otherwise, they may experience failures in
   the future if the service becomes more restrictive. When unthrottled, keep-alives can cause a
   significant amount of traffic and CPU usage, so clients and servers should be conservative in
   what they use and accept.

* *permit-keep-alive-without-calls*: Sets whether to allow clients to send keep-alive HTTP/2 PINGs even if there are no outstanding
   RPCs on the connection. The type is `boolean`, and the default is false.

* *protocol-provider*: Sets the `SslContext` implementation to use. The type is `String`. The default is
   OPENSSL if it is available. Otherwise, the default is JDK.

* *server-host*: The host to which the server is to be bound. The type is `String`, and the default is "localhost".

* *server-port*: The port to which the server is to be bound. The type is `int` and the default is 9555.

* *session-cache-size*: Set the size of the cache used for storing SSL session objects. The type is `long` and the
   default depends on the `SslContext` implementation.

* *session-timeout*: Set the timeout for the cached SSL session objects, in seconds. The type is `long` and the
   default depends on the `SslContext` implementation.

* *shutdown-timeout*: Sets the time that the server should wait to become terminated, giving up if the timeout
   is reached. The type is `int`, and the default is 3 seconds.

* *ssl-context-name*: Refers to an SSL Context defined in the Elytron subsystem. The type is `String` and no value
   is set by default.
  
* *start-tls*: Sets whether the first write request shouldn't be encrypted. The type is `boolean` and the default
   depends on the `SslContext` implementation.
   
* *trust-manager-name*: Refers to a trust manager defined in the Elytron subsystem. The type is `String`. No trust manager
   is set by default.
////
=== Deployment

gRPC services, clients and interceptors are deployed to WildFly using Jakarta EE deployments. Configuration is applied using a deployment descriptor.

==== Deployment Descriptor

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<grpc xmlns="urn:wildfly:grpc:1.0">
    <server>
        <host>localhost</host>
        <port>9001</port>
        <security>
            <plain-text>true</plain-text>
            <key-manager>keyManager</key-manager>
        </security>
        <services>
            <service>
                <class>com.acme.GrpcService1</class>
                <interceptors>
                    <interceptor>
                        <class>com.acme.GrpcInterceptor1</class>
                        <priority>10</priority>
                    </interceptor>
                    <interceptor>
                        <class>com.acme.GrpcInterceptor2</class>
                        <priority>20</priority>
                    </interceptor>
                </interceptors>
            </service>
            <service>
                <class>com.acme.GrpcService2</class>
            </service>
        </services>
        <interceptors>
            <interceptor>
                <class>com.acme.GrpcInterceptor1</class>
            </interceptor>
            <interceptor>
                <class>com.acme.GrpcInterceptor2</class>
            </interceptor>
        </interceptors>
        <!--
            Other setting like timeouts, message size,
            compression (see above).
        -->
    </server>
    <clients>
        <client>
            <name>hello</name>
            <host>localhost</host>
            <port>9001</port>
            <security>
                <plain-text>true</plain-text>
                <key-manager>keyManager</key-manager>
            </security>
            <interceptors>
                <interceptor>
                    <class>com.acme.GrpcInterceptor1</class>
                    <priority>10</priority>
                </interceptor>
                <interceptor>
                    <class>com.acme.GrpcInterceptor2</class>
                    <priority>20</priority>
                </interceptor>
            </interceptors>
            <!--
                Other setting like timeouts, message size,
                compression (see above).
            -->
        </client>
    </clients>
</grpc>
////
=== Development Model

==== Services

To implement a gRPC service, the class has to extend the generated gRPC implementation base and override the methods defined in the service interface.

==== Server Interceptors

A gRPC server interceptor has to implement `io.grpc.ServerInterceptor`. All server interceptors found in a gRPC
WAR are applied to all services in that WAR. They are applied in order as determined by
the `jakarta.annotation.Priority`.

////
==== Clients

gRPC clients can be created using channels. The channel can be injected referencing the name given in the deployment descriptor. Using the channel both a blocking/synchronous clients and non-blocking/asynchronous clients can be created.

==== Client Interceptors

A gRPC client interceptor has to implement `io.grpc.ClientInterceptor` and is applied to a gRPC client using an annotation or the deployment descriptor.
////
== Test Plan

=== Unit tests

* Usual `SubsystemTestCase`, with and without expressions

=== Integration tests

* unary calls
 ** plaintext
 ** client authentication
 ** client and server authentication
 
* bidirectional streaming
 ** plaintext
 ** client authentication
 ** client and server authentication
 
* server interceptor tests
 ** unary calls
 ** streaming
 ** segregation of interceptors by WARs
 ** ordering by @Priority
 
=== Nice to have tests

Integration tests that verify the setting of each of the parameters
  

== Community Documentation

Detailed description in pull request https://github.com/wildfly/wildfly/pull/18256[WFLY-15495: Adding a chapter on the grpc subsystem]. 
